import os
import re
from pathlib import Path

import markdown
from weasyprint import HTML


GENERATED_REPORTS_DIR = Path("generated_reports")


def sanitize_filename(value: str) -> str:
    value = re.sub(r"[^a-zA-Z0-9-_]", "_", value)
    return value[:120]


def markdown_to_html(markdown_text: str, title: str) -> str:
    html_body = markdown.markdown(
        markdown_text or "",
        extensions=[
            "extra",
            "sane_lists",
            "nl2br",
        ],
    )

    return f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>{title}</title>
  <style>
    @page {{
      size: A4;
      margin: 24mm 18mm;
    }}

    body {{
      font-family: Arial, sans-serif;
      color: #0f172a;
      line-height: 1.6;
      font-size: 12px;
    }}

    h1 {{
      font-size: 24px;
      color: #1e3a8a;
      margin-bottom: 16px;
      border-bottom: 2px solid #e2e8f0;
      padding-bottom: 10px;
    }}

    h2 {{
      font-size: 18px;
      color: #1e40af;
      margin-top: 24px;
      margin-bottom: 10px;
    }}

    h3 {{
      font-size: 15px;
      color: #334155;
      margin-top: 18px;
    }}

    p {{
      margin: 8px 0;
    }}

    ul, ol {{
      margin-top: 8px;
      margin-bottom: 12px;
      padding-left: 22px;
    }}

    li {{
      margin-bottom: 6px;
    }}

    code {{
      background: #f1f5f9;
      padding: 2px 5px;
      border-radius: 4px;
    }}

    .footer {{
      margin-top: 36px;
      padding-top: 12px;
      border-top: 1px solid #e2e8f0;
      font-size: 10px;
      color: #64748b;
    }}
  </style>
</head>
<body>
  {html_body}

  <div class="footer">
    Generated by OutreachPilot AI. Review all facts before sending outreach.
  </div>
</body>
</html>
"""


def generate_report_pdf(
    report_id: str,
    report_markdown: str,
    title: str,
) -> str:
    GENERATED_REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    safe_report_id = sanitize_filename(report_id)
    pdf_path = GENERATED_REPORTS_DIR / f"{safe_report_id}.pdf"

    html_content = markdown_to_html(
        markdown_text=report_markdown,
        title=title,
    )

    HTML(string=html_content).write_pdf(str(pdf_path))

    return str(pdf_path)